# Generated by Django 5.1.2 on 2024-10-21 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image1", models.ImageField(upload_to="texts/")),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="texts/"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="texts/"),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, null=True, upload_to="texts/"),
                ),
                (
                    "image5",
                    models.ImageField(blank=True, null=True, upload_to="texts/"),
                ),
                (
                    "image6",
                    models.ImageField(blank=True, null=True, upload_to="texts/"),
                ),
                (
                    "image7",
                    models.ImageField(blank=True, null=True, upload_to="texts/"),
                ),
                (
                    "image8",
                    models.ImageField(blank=True, null=True, upload_to="texts/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image1", models.ImageField(upload_to="books/")),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="books/"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="books/"),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, null=True, upload_to="books/"),
                ),
                (
                    "image5",
                    models.ImageField(blank=True, null=True, upload_to="books/"),
                ),
                ("type", models.CharField(max_length=50)),
                ("text", models.ManyToManyField(related_name="books", to="book.text")),
            ],
        ),
    ]
