# Generated by Django 5.1.2 on 2024-11-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_image1_alter_book_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
