# Generated by Django 5.1.2 on 2024-11-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_book_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
