# Generated by Django 5.1.2 on 2024-11-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_book_image1_alter_book_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image1",
            field=models.ImageField(upload_to="media"),
        ),
        migrations.AlterField(
            model_name="book",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="book",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="book",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="book",
            name="image5",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="text",
            name="image1",
            field=models.ImageField(upload_to="media"),
        ),
        migrations.AlterField(
            model_name="text",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="text",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="text",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="text",
            name="image5",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="text",
            name="image6",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="text",
            name="image7",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="text",
            name="image8",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
