# Generated by Django 5.1.2 on 2024-11-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_book_image1_alter_book_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="text",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="books", to="book.text"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
