# Generated by Django 5.1.2 on 2024-11-20 08:21

import book.s3field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_alter_book_image1_alter_book_image2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="text",
            name="image8",
        ),
        migrations.AlterField(
            model_name="book",
            name="image1",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="image2",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="image3",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="image4",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="image5",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="text",
            name="image1",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="text",
            name="image2",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="text",
            name="image3",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="text",
            name="image4",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="text",
            name="image5",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="text",
            name="image6",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="text",
            name="image7",
            field=book.s3field.S3FileField(blank=True, null=True, upload_to=""),
        ),
    ]
